apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: cooly-crawler
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  Cooly Registry
      status: Connected to the Cooly Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 15
        instance-info-replication-interval-seconds: 15
        registry-fetch-interval-seconds: 15
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 15
      instance:
        lease-renewal-interval-in-seconds: 10
        registry-default-open-for-traffic-count: 0
    coolybot:
      security:
        authentication:
          jwt:
            base64-secret: M2E0ZGYzOGRhNTZjNGUyYjJiMmE0ZGZkMGJhMmU0Y2UzMDg1MzZmYWI2Y2ZlNWMxYTdkYTE1ODhmMGI1ZWE1ZTVhOTQxY2RkNjNjNmJkMDM5YmE2YzI5NmRjMDJhOWNhNmQ1NA==
  # app specific configuration
  cooly-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@cooly-registry-0.cooly-registry.cooly-crawler.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@cooly-registry-1.cooly-registry.cooly-crawler.svc.cluster.local:8761/eureka/
